name: Docker

on:
  push:
    branch:
    - "master"
    tag:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        version:
        - "1.25.10"
        - "1.26.5"
        - "1.27.2"
        include:
        - version: "1.27.2"
          latest: true

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup - buildx
      uses: docker/setup-buildx-action@v2

    - name: Setup - Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup - Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Setup - Docker image metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |-
          swaglive/kubectl
          ghcr.io/${{ github.repository_owner }}/kubectl
        flavor: |-
          latest=${{ !!matrix.latest }}
        tags: |-
          type=semver,pattern={{major}}.{{minor}},value=${{ matrix.version }}
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ matrix.version }}

    - name: Build
      uses: docker/build-push-action@v5
      id: build
      with:
        context: .
        build-args: |
          version=${{ matrix.version }}
        push: true
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max